-- ============================================================================
-- Migration: 2026-08-07_rbac_capabilities
-- Purpose:   Implementar RBAC granular con 3 roles (cio, analyst, viewer)
--            y 104 capacidades atómicas.
-- Author:    IT team
-- Rollback:  DROP TABLE role_capabilities; DROP TABLE capabilities;
--            ALTER TABLE admin_users DROP CONSTRAINT admin_users_role_check;
--            (los usuarios 'cio' quedarán con role='cio' pero el helper hace fallback)
-- ============================================================================

-- 1. Tabla catálogo de capacidades
CREATE TABLE IF NOT EXISTS public.capabilities (
  id           TEXT PRIMARY KEY,
  domain       TEXT NOT NULL,
  description  TEXT NOT NULL,
  endpoint     TEXT,
  criticality  CHAR(1) NOT NULL CHECK (criticality IN ('A','M','B')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.capabilities IS 'Catálogo maestro de capacidades del sistema RBAC.';

CREATE INDEX IF NOT EXISTS idx_capabilities_domain ON public.capabilities(domain);

-- 2. Tabla de asignaciones rol -> capacidad
CREATE TABLE IF NOT EXISTS public.role_capabilities (
  role           TEXT NOT NULL,
  capability_id  TEXT NOT NULL REFERENCES public.capabilities(id) ON DELETE CASCADE,
  granted        BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (role, capability_id)
);
COMMENT ON TABLE public.role_capabilities IS 'Matriz de asignación de capacidades a roles (cio/analyst/viewer).';

CREATE INDEX IF NOT EXISTS idx_role_capabilities_role ON public.role_capabilities(role);

-- 3. Ampliar rol permitido en admin_users
ALTER TABLE public.admin_users DROP CONSTRAINT IF EXISTS admin_users_role_check;
ALTER TABLE public.admin_users
  ADD CONSTRAINT admin_users_role_check
  CHECK (role IN ('admin', 'cio', 'analyst', 'viewer'));

-- 4. Migrar admin -> cio para luis (el único admin actual)
UPDATE public.admin_users SET role = 'cio' WHERE email = 'luis@dceholdings.com';

-- 5. Seed del catálogo de capacidades
INSERT INTO public.capabilities (id, domain, description, endpoint, criticality) VALUES
  ('DJ-01', 'Decision Journal', 'Ver el historial de decisiones (BUY/SELL/PASS)', 'GET /api/journal', 'B'),
  ('DJ-02', 'Decision Journal', 'Ver el PDF exportable de una decisión', 'GET /api/decision-pdf', 'B'),
  ('DJ-03', 'Decision Journal', 'Crear entrada BUY (registra inversión nueva)', 'POST /api/admin/journal (buy)', 'A'),
  ('DJ-04', 'Decision Journal', 'Crear entrada SELL (cerrar posición + post-mortem)', 'POST /api/admin/journal (sell)', 'A'),
  ('DJ-05', 'Decision Journal', 'Crear entrada PASS (descartar tras research)', 'POST /api/admin/journal (pass)', 'M'),
  ('DJ-06', 'Decision Journal', 'Modificar la thesis o metadata de una entrada existente', 'PATCH /api/admin/journal', 'A'),
  ('DJ-07', 'Decision Journal', 'Eliminar una entrada del journal', 'DELETE /api/admin/journal', 'A'),
  ('DJ-08', 'Decision Journal', 'Ver decision_inputs.json (pre-fill del Munger v4)', 'GET /api/journal-decision-inputs', 'B'),
  ('PL-01', 'Pipeline', 'Ver el kanban del pipeline (backlog → invested)', 'GET /api/admin/pipeline-cards', 'B'),
  ('PL-02', 'Pipeline', 'Crear tarjeta nueva (añadir ticker al pipeline)', 'POST /api/admin/pipeline-cards', 'M'),
  ('PL-03', 'Pipeline', 'Mover tarjeta entre stages', 'PATCH /api/admin/pipeline-cards (stage)', 'M'),
  ('PL-04', 'Pipeline', 'Eliminar una tarjeta del pipeline', 'DELETE /api/admin/pipeline-cards', 'A'),
  ('PL-05', 'Pipeline', 'Añadir comentarios a una tarjeta', 'POST /api/admin/pipeline-comments', 'B'),
  ('PL-06', 'Pipeline', 'Subir assets (Excel, PDFs) a una tarjeta', 'POST /api/admin/pipeline-card-upload', 'M'),
  ('PL-07', 'Pipeline', 'Ver assets de todas las tarjetas', 'GET /api/admin/pipeline-card-assets-all', 'B'),
  ('PL-08', 'Pipeline', 'Generar dashboard interactivo desde Columbia model', 'POST /api/admin/pipeline-card-generate-dashboard', 'M'),
  ('PL-09', 'Pipeline', 'Publicar dashboard como /company.html?t=TICKER', 'POST /api/admin/pipeline-card-publish-dashboard', 'M'),
  ('RU-01', 'Re-underwriting', 'Ver dues pendientes de re-underwriting', 'GET /api/reunderwriting-due', 'B'),
  ('RU-02', 'Re-underwriting', 'Ver detalle de un due', 'GET /api/reunderwriting-detail', 'B'),
  ('RU-03', 'Re-underwriting', 'Ver PDF exportable del re-underwriting', 'GET /api/reunderwriting-pdf', 'B'),
  ('RU-04', 'Re-underwriting', 'Firmar (submit) un re-underwriting con veredicto', 'POST /api/reunderwriting-submit', 'A'),
  ('RU-05', 'Re-underwriting', 'Deshacer un re-underwriting ya firmado (undo)', 'POST /api/reunderwriting-undo', 'A'),
  ('RU-06', 'Re-underwriting', 'Ver pre-fill del re-underwriting antes de firmar', 'GET /api/reunderwriting-prefill', 'B'),
  ('PF-01', 'Portfolio', 'Ver listado de transacciones', 'GET /api/list-transactions', 'B'),
  ('PF-02', 'Portfolio', 'Añadir transacción manual', 'POST /api/admin-add-manual-entry', 'M'),
  ('PF-03', 'Portfolio', 'Eliminar transacción', 'DELETE /api/delete-transaction', 'A'),
  ('PF-04', 'Portfolio', 'Registrar trade (BUY/SELL asociado a journal entry)', 'POST /api/trades', 'M'),
  ('PF-05', 'Portfolio', 'Ver performance del portafolio', 'GET /api/performance', 'B'),
  ('PF-06', 'Portfolio', 'Ver cockpit (resumen ejecutivo diario)', 'GET /api/cockpit / /api/cockpit-summary', 'B'),
  ('PF-07', 'Portfolio', 'Ver dividendos pendientes', 'GET /api/dividend-pending', 'B'),
  ('PF-08', 'Portfolio', 'Ver time deposits (renta fija)', 'GET /api/time-deposits', 'B'),
  ('PF-09', 'Portfolio', 'Editar/crear time deposit', 'POST/PATCH /api/time-deposits', 'M'),
  ('IM-01', 'Imports', 'Ver historial de imports', 'GET /api/list-imports', 'B'),
  ('IM-02', 'Imports', 'Importar statement de Schwab', 'POST /api/admin-import-schwab', 'M'),
  ('IM-03', 'Imports', 'Eliminar un import (rollback)', 'DELETE /api/delete-import', 'A'),
  ('IM-04', 'Imports', 'Ver status de statements de Schwab', 'GET /api/schwab-statement-status', 'B'),
  ('PMM-01', 'Pre-mortems', 'Ver pre-mortems activos', 'GET /api/premortems', 'B'),
  ('PMM-02', 'Pre-mortems', 'Ver historial de versiones de pre-mortems', 'GET /api/premortem-history', 'B'),
  ('PMM-03', 'Pre-mortems', 'Crear/actualizar un pre-mortem', 'POST /api/admin/premortems', 'M'),
  ('PMM-04', 'Pre-mortems', 'Evaluar failure modes contra el pre-mortem (automatic eval)', 'POST /api/admin-premortem-eval', 'M'),
  ('FM-01', 'Failure Modes', 'Ver failure modes definidos', 'GET /api/failure-modes', 'B'),
  ('FM-02', 'Failure Modes', 'Definir/editar failure modes', 'POST /api/admin/failure-modes', 'M'),
  ('DR-01', 'Discipline', 'Ver reglas de disciplina activas', 'GET /api/discipline-rules', 'B'),
  ('DR-02', 'Discipline', 'Crear/editar regla de disciplina', 'POST /api/admin-discipline-rules', 'M'),
  ('DR-03', 'Discipline', 'Ejecutar evaluación de reglas de disciplina', 'POST /api/admin-discipline-eval', 'M'),
  ('WL-01', 'Watchlist', 'Ver watchlist propia', 'GET /api/watchlist', 'B'),
  ('WL-02', 'Watchlist', 'Añadir/quitar tickers de watchlist admin (global)', 'POST/DELETE /api/admin-watchlist', 'M'),
  ('SC-01', 'Screener', 'Consultar el último screener corrido', 'GET /api/screener-query', 'B'),
  ('SC-02', 'Screener', 'Forzar refresh manual del screener', 'POST /api/admin/screener-refresh-now', 'M'),
  ('DTR-01', 'Data Room', 'Ver documentos del Data Room', 'GET /api/source-documents / dataroom-files', 'B'),
  ('DTR-02', 'Data Room', 'Subir documento al Data Room', 'POST /api/admin/dataroom-upload', 'M'),
  ('DTR-03', 'Data Room', 'Crear/editar carpetas del Data Room', 'POST/PATCH /api/admin/dataroom-folders', 'M'),
  ('DTR-04', 'Data Room', 'Eliminar documentos del Data Room', 'DELETE /api/admin/dataroom-files', 'A'),
  ('DTR-05', 'Data Room', 'Ver archivos subidos por otros usuarios', 'GET /api/admin/dataroom-uploaded-files', 'B'),
  ('DTR-06', 'Data Room', 'Ingesta bulk de documentos vía LLM', 'POST /api/admin-ingest-docs', 'M'),
  ('RP-01', 'Reports', 'Ver histórico de reports', 'GET /api/list-reports', 'B'),
  ('RP-02', 'Reports', 'Generar daily report', 'POST /api/generate-daily-report', 'M'),
  ('RP-03', 'Reports', 'Generar consolidated report', 'POST /api/generate-consolidated-report', 'M'),
  ('RP-04', 'Reports', 'Generar crypto report', 'POST /api/generate-crypto-report', 'M'),
  ('RP-05', 'Reports', 'Generar real estate report', 'POST /api/generate-real-estate-report', 'M'),
  ('RP-06', 'Reports', 'Generar fixed income report', 'POST /api/generate-fixed-income-report', 'M'),
  ('RP-07', 'Reports', 'Subir report manualmente', 'POST /api/upload-report', 'M'),
  ('RP-08', 'Reports', 'Eliminar un report', 'DELETE /api/delete-report', 'A'),
  ('DB-01', 'Dashboards', 'Ver dashboard de una empresa (/company.html)', 'GET /company.html', 'B'),
  ('DB-02', 'Dashboards', 'Ver universe de dashboards publicados', 'GET /api/dashboard-universe-rows', 'B'),
  ('DB-03', 'Dashboards', 'Ver histórico de versiones de un dashboard', 'GET /api/list-dashboard-versions', 'B'),
  ('DB-04', 'Dashboards', 'Publicar/upsert dashboard JSON', 'POST /api/admin/upsert-dashboard', 'M'),
  ('DB-05', 'Dashboards', 'Seed batch de dashboards', 'POST /api/admin/seed-dashboards', 'M'),
  ('IF-01', 'Idea Feed', 'Ver feed agregado de ideas', 'GET /api/idea-feed', 'B'),
  ('IF-02', 'Idea Feed', 'Gestionar fuentes de idea feed', 'POST/DELETE /api/admin/idea-feed-sources', 'M'),
  ('IF-03', 'Idea Feed', 'Forzar refresh del feed', 'POST /api/admin/refresh-feed-now', 'M'),
  ('IF-04', 'Idea Feed', 'Eliminar una fuente de ideas', 'DELETE /api/delete-source', 'A'),
  ('AL-01', 'Alerts', 'Ver alertas del sistema', 'GET /api/alerts', 'B'),
  ('AL-02', 'Alerts', 'Configurar/gestionar alertas', 'POST /api/admin/alerts', 'M'),
  ('ST-01', 'Study', 'Ver materiales de study', 'GET /api/study', 'B'),
  ('ST-02', 'Study', 'Subir materiales de study', 'POST /api/admin/study-upload', 'M'),
  ('ST-03', 'Study', 'Eliminar materiales de study', 'DELETE /api/admin/study-files', 'M'),
  ('EA-01', 'Earnings', 'Ver calendario y datos de earnings', 'GET /api/earnings', 'B'),
  ('EA-02', 'Earnings', 'Forzar refresh manual de earnings', 'POST /api/admin/earnings-refresh-now', 'M'),
  ('EA-03', 'Earnings', 'Ver tickers monitoreados de earnings', 'GET /api/admin/earnings-tickers', 'B'),
  ('IV-01', 'IV Tracking', 'Ver IV tracking de tickers', 'GET /api/iv-tracking / /api/admin/iv-tracking', 'B'),
  ('RD-01', 'Radar', 'Ver radar de tickers cubiertos', 'GET /api/admin/radar', 'B'),
  ('AN-01', 'Analysts', 'Gestionar directorio de analystas', 'POST /api/admin/analysts', 'M'),
  ('TM-01', 'Team', 'Ver actas de team meetings', 'GET /api/team-meetings', 'B'),
  ('TM-02', 'Team', 'Crear/editar actas de team meetings', 'POST /api/team-meetings', 'M'),
  ('NW-01', 'News', 'Ver news feed de tickers', 'GET /api/news-tickers', 'B'),
  ('SL-01', 'Slack', 'Ver inbox de Slack integrada', 'GET /api/slack-inbox', 'B'),
  ('SL-02', 'Slack', 'Enviar mensajes a Slack (send)', 'POST /api/send', 'M'),
  ('US-01', 'Users', 'Ver listado de usuarios del sistema', 'GET /api/admin/users', 'B'),
  ('US-02', 'Users', 'Crear usuario nuevo', 'POST /api/admin/users', 'A'),
  ('US-03', 'Users', 'Editar rol/estado de un usuario', 'PATCH /api/admin/users', 'A'),
  ('US-04', 'Users', 'Desactivar/eliminar usuario', 'DELETE /api/admin/users', 'A'),
  ('US-05', 'Users', 'Ver logs de login', 'GET /api/admin/audit-logins', 'B'),
  ('US-06', 'Users', 'Ver audit log general', 'GET /api/list-audit', 'B'),
  ('SY-01', 'System', 'Ver status de backups nightly', 'GET /api/admin/backup-status', 'B'),
  ('SY-02', 'System', 'Disparar cron manual (backup, snapshot, etc.)', 'POST /api/admin/run-cron', 'A'),
  ('SY-03', 'System', 'Backfill de precios históricos', 'POST /api/admin-backfill-prices', 'M'),
  ('SY-04', 'System', 'Backfill de snapshots de portfolio', 'POST /api/admin-backfill-snapshots', 'M'),
  ('SY-05', 'System', 'Backfill de mirror del pipeline', 'POST /api/admin/pipeline-mirror-backfill', 'M'),
  ('SY-06', 'System', 'Backfill de decision → dataroom', 'POST /api/admin/decision-dataroom-backfill', 'M'),
  ('AU-01', 'Auth', 'Login (todos los usuarios activos)', 'POST /api/admin-login', 'B'),
  ('AU-02', 'Auth', 'Cambiar password propio', 'POST /api/auth/change-password', 'B'),
  ('AU-03', 'Auth', 'Configurar WebAuthn/passkey propio', 'POST /api/auth/webauthn-*', 'B'),
  ('AU-04', 'Auth', 'Ver info propia (/me)', 'GET /api/me', 'B')
ON CONFLICT (id) DO UPDATE SET
  domain = EXCLUDED.domain,
  description = EXCLUDED.description,
  endpoint = EXCLUDED.endpoint,
  criticality = EXCLUDED.criticality;

-- 6. Seed de asignaciones rol → capacidad (solo las 'granted = true')
INSERT INTO public.role_capabilities (role, capability_id, granted) VALUES
  ('cio', 'DJ-01', true),
  ('analyst', 'DJ-01', true),
  ('viewer', 'DJ-01', true),
  ('cio', 'DJ-02', true),
  ('analyst', 'DJ-02', true),
  ('viewer', 'DJ-02', true),
  ('cio', 'DJ-03', true),
  ('cio', 'DJ-04', true),
  ('cio', 'DJ-05', true),
  ('cio', 'DJ-06', true),
  ('cio', 'DJ-07', true),
  ('cio', 'DJ-08', true),
  ('analyst', 'DJ-08', true),
  ('cio', 'PL-01', true),
  ('analyst', 'PL-01', true),
  ('cio', 'PL-02', true),
  ('analyst', 'PL-02', true),
  ('cio', 'PL-03', true),
  ('analyst', 'PL-03', true),
  ('cio', 'PL-04', true),
  ('cio', 'PL-05', true),
  ('analyst', 'PL-05', true),
  ('cio', 'PL-06', true),
  ('analyst', 'PL-06', true),
  ('cio', 'PL-07', true),
  ('analyst', 'PL-07', true),
  ('cio', 'PL-08', true),
  ('analyst', 'PL-08', true),
  ('cio', 'PL-09', true),
  ('cio', 'RU-01', true),
  ('analyst', 'RU-01', true),
  ('cio', 'RU-02', true),
  ('analyst', 'RU-02', true),
  ('viewer', 'RU-02', true),
  ('cio', 'RU-03', true),
  ('analyst', 'RU-03', true),
  ('viewer', 'RU-03', true),
  ('cio', 'RU-04', true),
  ('cio', 'RU-05', true),
  ('cio', 'RU-06', true),
  ('analyst', 'RU-06', true),
  ('cio', 'PF-01', true),
  ('analyst', 'PF-01', true),
  ('cio', 'PF-02', true),
  ('cio', 'PF-03', true),
  ('cio', 'PF-04', true),
  ('cio', 'PF-05', true),
  ('analyst', 'PF-05', true),
  ('viewer', 'PF-05', true),
  ('cio', 'PF-06', true),
  ('analyst', 'PF-06', true),
  ('cio', 'PF-07', true),
  ('analyst', 'PF-07', true),
  ('cio', 'PF-08', true),
  ('analyst', 'PF-08', true),
  ('cio', 'PF-09', true),
  ('cio', 'IM-01', true),
  ('analyst', 'IM-01', true),
  ('cio', 'IM-02', true),
  ('cio', 'IM-03', true),
  ('cio', 'IM-04', true),
  ('analyst', 'IM-04', true),
  ('cio', 'PMM-01', true),
  ('analyst', 'PMM-01', true),
  ('cio', 'PMM-02', true),
  ('analyst', 'PMM-02', true),
  ('cio', 'PMM-03', true),
  ('analyst', 'PMM-03', true),
  ('cio', 'PMM-04', true),
  ('analyst', 'PMM-04', true),
  ('cio', 'FM-01', true),
  ('analyst', 'FM-01', true),
  ('cio', 'FM-02', true),
  ('analyst', 'FM-02', true),
  ('cio', 'DR-01', true),
  ('analyst', 'DR-01', true),
  ('cio', 'DR-02', true),
  ('cio', 'DR-03', true),
  ('analyst', 'DR-03', true),
  ('cio', 'WL-01', true),
  ('analyst', 'WL-01', true),
  ('cio', 'WL-02', true),
  ('cio', 'SC-01', true),
  ('analyst', 'SC-01', true),
  ('cio', 'SC-02', true),
  ('analyst', 'SC-02', true),
  ('cio', 'DTR-01', true),
  ('analyst', 'DTR-01', true),
  ('cio', 'DTR-02', true),
  ('analyst', 'DTR-02', true),
  ('cio', 'DTR-03', true),
  ('analyst', 'DTR-03', true),
  ('cio', 'DTR-04', true),
  ('cio', 'DTR-05', true),
  ('analyst', 'DTR-05', true),
  ('cio', 'DTR-06', true),
  ('analyst', 'DTR-06', true),
  ('cio', 'RP-01', true),
  ('analyst', 'RP-01', true),
  ('viewer', 'RP-01', true),
  ('cio', 'RP-02', true),
  ('analyst', 'RP-02', true),
  ('cio', 'RP-03', true),
  ('analyst', 'RP-03', true),
  ('cio', 'RP-04', true),
  ('analyst', 'RP-04', true),
  ('cio', 'RP-05', true),
  ('analyst', 'RP-05', true),
  ('cio', 'RP-06', true),
  ('analyst', 'RP-06', true),
  ('cio', 'RP-07', true),
  ('analyst', 'RP-07', true),
  ('cio', 'RP-08', true),
  ('cio', 'DB-01', true),
  ('analyst', 'DB-01', true),
  ('viewer', 'DB-01', true),
  ('cio', 'DB-02', true),
  ('analyst', 'DB-02', true),
  ('viewer', 'DB-02', true),
  ('cio', 'DB-03', true),
  ('analyst', 'DB-03', true),
  ('cio', 'DB-04', true),
  ('cio', 'DB-05', true),
  ('cio', 'IF-01', true),
  ('analyst', 'IF-01', true),
  ('cio', 'IF-02', true),
  ('analyst', 'IF-02', true),
  ('cio', 'IF-03', true),
  ('analyst', 'IF-03', true),
  ('cio', 'IF-04', true),
  ('cio', 'AL-01', true),
  ('analyst', 'AL-01', true),
  ('cio', 'AL-02', true),
  ('cio', 'ST-01', true),
  ('analyst', 'ST-01', true),
  ('viewer', 'ST-01', true),
  ('cio', 'ST-02', true),
  ('analyst', 'ST-02', true),
  ('cio', 'ST-03', true),
  ('cio', 'EA-01', true),
  ('analyst', 'EA-01', true),
  ('cio', 'EA-02', true),
  ('analyst', 'EA-02', true),
  ('cio', 'EA-03', true),
  ('analyst', 'EA-03', true),
  ('cio', 'IV-01', true),
  ('analyst', 'IV-01', true),
  ('cio', 'RD-01', true),
  ('analyst', 'RD-01', true),
  ('cio', 'AN-01', true),
  ('cio', 'TM-01', true),
  ('analyst', 'TM-01', true),
  ('cio', 'TM-02', true),
  ('analyst', 'TM-02', true),
  ('cio', 'NW-01', true),
  ('analyst', 'NW-01', true),
  ('cio', 'SL-01', true),
  ('analyst', 'SL-01', true),
  ('cio', 'SL-02', true),
  ('cio', 'US-01', true),
  ('cio', 'US-02', true),
  ('cio', 'US-03', true),
  ('cio', 'US-04', true),
  ('cio', 'US-05', true),
  ('cio', 'US-06', true),
  ('cio', 'SY-01', true),
  ('cio', 'SY-02', true),
  ('cio', 'SY-03', true),
  ('cio', 'SY-04', true),
  ('cio', 'SY-05', true),
  ('cio', 'SY-06', true),
  ('cio', 'AU-01', true),
  ('analyst', 'AU-01', true),
  ('viewer', 'AU-01', true),
  ('cio', 'AU-02', true),
  ('analyst', 'AU-02', true),
  ('viewer', 'AU-02', true),
  ('cio', 'AU-03', true),
  ('analyst', 'AU-03', true),
  ('viewer', 'AU-03', true),
  ('cio', 'AU-04', true),
  ('analyst', 'AU-04', true),
  ('viewer', 'AU-04', true)
ON CONFLICT (role, capability_id) DO UPDATE SET granted = EXCLUDED.granted;

-- 7. RLS: solo lectura vía service role (cliente no accede directo)
ALTER TABLE public.capabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_capabilities ENABLE ROW LEVEL SECURITY;
-- No policies definidas: solo service_role (backend) puede leer/escribir.

-- 8. Verificación (informativa)
-- SELECT role, COUNT(*) FROM role_capabilities WHERE granted = true GROUP BY role ORDER BY role;
-- Debe devolver: cio=104, analyst=66, viewer=13